### ISSUE TITLE
[Bug] Scheduling recurring CalDAV events

### ISSUE THREAD

**Issue by smac89** [SimpleMobileTools/Simple-Calendar#1201]
I use calendar extensively and recently switched from DigiCal (an excellent calendar manager) to SimpleCalendar. Yesterday I started to notice that events were not correctly being synced to SimpleCalendar over CalDAV. I use DAVx5 btw.

Here is the exact problem:

- On my computer, I use Evolution to create an event that occurs every 5th Wednesday starting on September 30th, 2020. I set this event to only repeat twice.
- On Evolution, I also check that event is created once for September 30th, 2020, and the next event is created for December 30th, 2020. I manually verify that these are the only days and within the range I specified which have a 5th Wednesday.
- On my phone when I refresh the event in SimpleCalendar, it created the one event for September 30th, 2020, **but it also creates another event for October 28th, 2020!**
- On another phone which also has DAVx but using DigiCal, I check my Calendar and the event is created as on Evolution: September, and December

I am using the latest version of Simple-Calendar Pro v6.10.0

**EDIT:**

I should also add that deleting the event on Evolution, also deletes the correct events on SimpleCalendar, so the problem is definitely with the way it displays recurring events.

Upon further testing my conclusion is that instead of showing the event every 5th Wednesday, it defaults to showing it as every last Wednesday, which is not the same thing

**EDIT2:**
Looks related to #963

**Comment by llevrel** [comment]
Hi,

I'm currently testing Simple Calendar before I buy Simple Calendar Pro and found a bug. So I searched here to find whether it had been corrected in the Pro version, and I found this bug which may be related. So I'm adding my report here, you can test if the bug is still here in the Pro version.

Steps to reproduce:
Create an all-day event starting Monday 2nd November, ending Sunday 8th November, repeating every 2 weeks.
Expected result: the event will appear on weeks with odd numbers in 2020 and even numbers in 2021, because 2020 has 53 numbered weeks. Since this event appears on week 53, it should next appear on week 2 of 2021.
Found result: the event appears also on odd weeks of 2021, so it happens on weeks 53 of 2020 and 1 of 2021, with no leap week in-between.

I see bug #1143 has the word biweekly in the title but no details are given. It is quite old... I consider incorrect computations of recurring events to be major bugs for a calendar app, I think they should have top priority! (bug #865 is more than 18 months old and still open...)

**Comment by smac89** [comment]
@llevrel I have the pro version and I just tested your scenario on the app, and it gives the expected results.

November 2nd, 2020 is week 45, and the event shows for weeks, 47, 49, 51, 53.
In 2021, it starts on Week 2, and ends on Week 44 which is November 1st, 2021
