### ISSUE TITLE
Importing ics files is case sensitive

### ISSUE THREAD

**Issue by StephanBussmann** [SimpleMobileTools/Simple-Calendar#1245]
Hello there, 

I noticed a minor bug when I wanted to import events from an ics file.
The file extension of the file I downloaded was in uppercase like for example "myEvents.ICS".
So, when I tried to import events from this file I could not choose it.
It seems this file is not recognised as an ics file.
After renaming the file I could choose it for an import.

Well, it is not a big deal, but was confusing at first.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by StephanBussmann** [comment]
I'm using v 6.11.2 Pro 
OS: Android 10
Nokia 7.2

**Comment by michaelof** [comment]
Hi Stefan,
strange error :)
same 6.11.2 pro (F-Droid)
Same mobile, Nokia 7.2, Android 10, like you.
I've created two files, A.ICS and B.ics. Empty files, created via Simple File Manager. Both are offered to get imported:
![Screenshot_20201203-211231](https://user-images.githubusercontent.com/15951622/101083105-c757d000-35ac-11eb-9436-35db161f6262.png)

**Comment by StephanBussmann** [comment]
Maybe it is a problem of the default file manager.
It seems .ICS is recognised as document :/

![filemanager](https://user-images.githubusercontent.com/35926690/101090455-f8d59900-35b6-11eb-9fbc-6cbd3ff334c6.png)

**Comment by michaelof** [comment]
Hallo Stephan :)
Do your files differ at the end, because what's visible on the screenshot is the same? File mgr, stock or simple file manager, disallow e.g. a.ics together with a.ICS, although underlying ext4 file system is case sensitive. Not sure if it's possible to "bypass" this, somehow, with side effects? Other aspect: Your file name is long, allowed of course. But I've seen something similar buggy with long-named PDFs: Got PDFs as Email attachements, K9-Mail. Saved them, Download folder. Tried to open from "saved" notification: fails, MuPDF. Tried to open via Simple File Mgr, fails also. Renamed file(s) to shorter names, opens fine with MuPDF. Not really reproducible

**Comment by StephanBussmann** [comment]
Hallo Michael,

I made another test with a.ICS and b.ics both could be choosen.
But this document is buggy. Although it is already deleted the normal file manager still shows it.
Maybe this is the same bug you mentioned, caused by long file names.

Okay then, ticket can be closed. There is no bug, just weird behaviour of android :D
