### ISSUE TITLE
Calender fails to add event with Invalid Format Exception - breaks other events in synchronized calendar

### ISSUE THREAD

**Issue by peterDSM** [SimpleMobileTools/Simple-Calendar#1258]
App Version: 6.11.3 (F-Droid)
Exception: java.lang.IllegalArgumentException: Invalid format: "Europe/Berlin;20201018T000000Z"

### Steps to reproduce:
1. Rename attached minimized example file to *.ics
2. Import into Simple Calendar.

[test.txt](https://github.com/SimpleMobileTools/Simple-Calendar/files/5761551/test.txt)

###Issue description:
The attached ics-File is a minimized version generated by humhub-ics (self-hosted social network) Feed. The calendar is imported via ICSx5. While Etar calendar (Android) and Thunderbird (Linux) are able to import simple calendar causes an exception.
The exceptions also breaks the parsing of other (more recent) events. Therefore, Simple Calendar becomes unusable with the whole calendar as recent events are not shown.
Validator (https://icalendar.org/validator.html) shows that the attached event is valid. However, I was not able to understand the specification in a short time. Therefore, the reason I think this is a valid event is only because Thunderbird and Etar can handle it correctly.

### Expected Behavior:
Simple Calendar shows the event as expected.

If there is anything else I can help on this, feel free to contact me.

**Comment by ForGorNorPor** [comment]
The problem seems to persist. This is the message I got with version 6.13.0 Pro
![exception](https://user-images.githubusercontent.com/16355173/109416354-f8824980-79bd-11eb-8aca-08fc08161cdb.png)

**Comment by peterDSM** [comment]
For me this seams to be fixed with 6.13.0 for the test.txt file mentioned above. However, my original humhub-generated *ics-file still causes the issue mentioned by @ForGorNorPor.
Unfortunately, I am quiet busy with some private stuff these days. As soon as I'll find some time, I'll try to file a new follow-up bug.

**Comment by tibbi** [comment]
I need some sample files to be able to fix it

**Comment by ForGorNorPor** [comment]
Any help how I can narrow this down? My calendar is huge. I would rather try to find the problematic format myself than to scrap all my personal details and upload my calendar here.
I did a search through an exported ics file but could not find the date mentioned in the exception.

**Comment by tibbi** [comment]
when does the error appear to you? At importing some file?

**Comment by ForGorNorPor** [comment]
Ok, I managed to track it down, by divide and conquering through my contags (ugh) just to find out that the date in question is just slightly different than in the error message which is why I didn't find it with a simple text search.
This is a calendar with only a single event and the EXDATE seems to be the issue.

> BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:TEST
X-APPLE-CALENDAR-COLOR:#ff00ff
REFRESH-INTERVAL;VALUE=DURATION:PT4H
X-PUBLISHED-TTL:PT4H
BEGIN:VEVENT
DTSTAMP:20210118T201427Z
UID:7d25a5f4-1732-4595-a72b-206902e2c3a7
SEQUENCE:1
SUMMARY:Test
DTSTART;VALUE=DATE:20170120
DTEND;VALUE=DATE:20170121
RRULE:FREQ=YEARLY
**EXDATE:20210120T010000**
CLASS:PUBLIC
CREATED:20160717T171753Z
END:VEVENT
END:VCALENDAR

[test.txt](https://github.com/SimpleMobileTools/Simple-Calendar/files/6079327/test.txt) (rename to .ics)

**Comment by tibbi** [comment]
it works just fine to me, guess Ill experiment with setting some different time zones. Thanks

**Comment by ForGorNorPor** [comment]
Seems to be fixed with the newest update: Thank you for your help!

**Comment by peterDSM** [comment]
I can confirm this is fixed for me, too. Thanks for your work.
