### ISSUE TITLE
Notifications allowed on do not disturb interrupting sleep and meetings

### ISSUE THREAD

**Issue by eggnog-armed** [SimpleMobileTools/Simple-Calendar#1525]
Hi simple mobile tools

Thanks for making simple calendar pro (SCP). I've made a 10 EUR donation via your website through PayPal. I use it with etesync.

I recommended simple calendar pro to my partner after I had been using it for a few weeks. Unfortunately SCP sent notifications (audio and visual) in an important meeting even though she had her phone on do not disturb mode. This makes her seem unprofessional.

A few days later SCP woke me up at night with notifications even though my phone was on do not disturb.

SCP is the only app on our phones that behaves in this way after a default installation and no changes to the notification settings.

It is not appropriate for SCP to behave in this way in its default install state. Please can you ensure it adheres to the phone's do not disturb setting by default.

https://github.com/SimpleMobileTools/Simple-Calendar/issues/1243

https://github.com/SimpleMobileTools/Simple-Calendar/issues/939

I have a pixel 3a graphene os, scp via f droid (android 12 5 October 2021).
She has a pixel 3a and the standard factory, scp via google play.

Thanks

**Comment by ayounggun** [comment]
Thanks for the reply. It might be worth making users aware that this tradeoff is being made i.e. choosing a notification type (alarm) that is allowed through the default do not disturb settings, in order to get better reliability of notifications overall.

My do not disturb and SCP settings above were all stock so it will most likely impact a few people over time, even if they do not say.
