### ISSUE TITLE
UI revamp for listview not ideal for widget

### ISSUE THREAD

**Issue by Spekkie** [SimpleMobileTools/Simple-Calendar#1553]
Hi, although I like the new design of the list view in the app, it makes the listview widget very cluttered, resulting for me that I can only see half the items in the widget list against the old listview...

**Comment by szpak** [comment]
I also have mixed feeling about the new view of the "Simple event list" and size of the items. However, in addition, there is too small/too less distinguish separation between days. With fast scrolling, it can be problematic to follow the current date. I've just checked the previous version and while it looked similar, it was much more noticeable (maybe because of a different rendering of the event items).
