### ISSUE TITLE
Are network calendars supported?

### ISSUE THREAD

**Issue by manuel-plavsic** [SimpleMobileTools/Simple-Calendar#1683]
I'd like to subscribe to a network calendar. Is this supported?

If this isn't possible with Simple Calendar, is there a calendar subscription app that is compatible with Simple Calendar?

**Comment by tibbi** [comment]
well since Simple Calendar is offline, it cannot take care of syncing the data between the device and the cloud directly. It needs a so called "sync adapter" for taking care of that syncing. For syncing via Google it is enough to have Google Calendar installed, it will take care of exchanging data between your device and the cloud. So if you have Google Calendar enabled on your device, you can try enabling "CalDAV sync" in the app settings, to see if some calendars show up. If the syncing is set up properly, you should see the same events in your device and on https://calendar.google.com/calendar/r . If you don't want to use Google, you can set up "DAVx5" app as the sync adapter too.

**Comment by manuel-plavsic** [comment]
I don't have play services.

The DAVx5 website recommends using ICSx5 for network calendars (https://www.davx5.com/faq/subscribe-ics-file). I did it, however Simple Calendar Pro does not detect it. However, it does detect my DAVx5 calendar. Can you also test with a subscribed calendar?

**Comment by tibbi** [comment]
it should work just fine, you mean that once you enabled CalDAV sync in the app settings, you dont see any available calendars?
