### ISSUE TITLE
feature request: View screen for a single entry

### ISSUE THREAD

**Issue by vanous** [SimpleMobileTools/Simple-Calendar#1705]
Thank you very much for all the effort.

When viewing an event which contains a link, it is currently not possible to "just view" it, without opening for editing. This means that if the event contains an URL (for example for a video call), one cannot open it by tapping.

Possible solution would be to have a "view" screen which would allow tapping on links and Close/Edit buttons for further actions.

I did not find anyone else mentioning but please feel free to link to an existing issue and close as duplicate.
Thank you

**Comment by piaci** [comment]
and then maybe the calendar would handle the view intent as well?

like:
Intent intent = new Intent(Intent.ACTION_VIEW);
intent.setData(Uri.parse("content://com.android.calendar/events/" +_id);

**Comment by dumblob** [comment]
I for myself am totally fine (actually I even prefer it) to have no "read-only view" and open the editing mode instead.

But YMMV and if this "read-only view" ever materializes, then so be it - but please make all its fields vertically stretched as described in https://github.com/SimpleMobileTools/Simple-Calendar/issues/1748 .

**Comment by dumblob** [comment]
> Everytime when i open an event to join a call there's the possibility that i change all future occurencies of this event only because i was not precise enough to just copy the link.

I have tried to mimick this but failed. Could you be more specific how to reproduce this? I did the following:

1. created an event with URL in the description field, invited at least one more person, made it recurring every day, and saved it
2. switched view to agenda
3. touched the newly created event
4. touched the URL leading my Android phone to switch to another app (in my case it was a web browser)
5. then I opened "application switcher" (on modern Android it is swiping from bottom upwards; on older Androis it is with a hardware bottom left button on Samsung devices and the hardware bottom right button on other devices), selected SimpleCalendar, touched behind the URL and added some random text
6. again opened "application switcher" as in (5) but instead closed SimpleCalendar by swiping right/left/up (depending on your launcher)
7. nothing unexpected happened and nothing got saved - so the event stayed in the original state

I can imagine though imagine you have a different kind of problem - namely you did not close SimpleCalendar as in (6) above but instead tried to close the view with a "left arrow" icon top left which is a "thumb away" of the "tick" ("save") icon. In which case I would say this is simply badly positioned buttons and definitely not a sign to add unnecessary functionality like read-only view.

**Comment by vanous** [comment]
> > Everytime when i open an event to join a call there's the possibility that i change all future occurencies of this event only because i was not precise enough to just copy the link.
> 
> I have tried to mimick this but failed. Could you be more specific how to reproduce this? I did the following:
> 
>     1. created an event with URL in the description field, invited at least one more person, made it recurring every day, and saved it
> 
>     2. switched view to agenda
> 
>     3. touched the newly created event
> 
>     4. touched the URL leading my Android phone to switch to another app (in my case it was a web browser)

Clicking the URL doesn't open app/browser but allows to edit the URL text (I am in edit mode, so this is correct behavior). This behavior I observe on Android 11 and Android 12. I noticed that if I long press on the URL, it offers Open item.

**Comment by thedmo** [comment]
@dumblob and @vanous:  The Error is definetively on my side. Sometimes in a hurry i'm a little clumsy and end up changing stuff by accident.

I get the 'open' option aswell when i mark the link since i'm on Android 11 (didn't know that, thanks). Simply Tapping on the link doesn't open it though.

All in all, its just an inconvenience and not breaking. I'm aware as well, that this is a feature request and nothing more. So no pressure from me. Just wanted +1 on the request.

**Comment by dumblob** [comment]
@vanous oh, I did not notice on newer androids URLs in text are being highlighted and offer editing options

Despite this interesting observation my point holds - there is basically only one way to **persist** the unwanted change. Namely by pressing `tick` icon instead of the `left arrow` icon on the top. And this very single situation is actually more difficult to achieve than anything on the screen (the `left arrow` icon has the biggest "padding" from any other interactive items on the whole screen).

So I am still not sure why this feature request?

(as I said above - I for myself e.g. find the `tick` and `trash bin` icons too close to each other which is IMHO a much bigger issue than having `left arrow` and `tick` icons already quite **far away** from each other)
