### ISSUE TITLE
Share calendar

### ISSUE THREAD

**Issue by REDIEZ** [SimpleMobileTools/Simple-Calendar#1706]
Hi,
how is it possible to share calendars with external people?
I could not find documentation. If it sexists, please tell me where to find it.
best, isabelle

**Comment by tibbi** [comment]
Hi, well since Simple Calendar is offline, it cannot take care of syncing the data between the device and the cloud directly. It needs a so called "sync adapter" for taking care of that syncing. For syncing via Google it is enough to have Google Calendar installed, it will take care of exchanging data between your device and the cloud. So if you have Google Calendar enabled on your device, you can try enabling "CalDAV sync" in the app settings, to see if some calendars show up. If the syncing is set up properly, you should see the same events in your device and on https://calendar.google.com/calendar/r . If you don't want to use Google, you can set up "DAVx5" app as the sync adapter too. We will write up some guides on it soon.

**Comment by REDIEZ** [comment]
Hi, thanks for the prompt answer.
I was going through the process of buying dav*5 but the country I am
leaving in, Luxembourg,  is not accepted yet foe the PayPal process.
So keep me updated when you allow it.
Best.

Le lun. 2 mai 2022 à 14:58, Tibor Kaputa ***@***.***> a
écrit :

**Comment by tibbi** [comment]
that is not our app. However, you can get it on f-droid too, it is at https://f-droid.org/packages/at.bitfire.davdroid/
