### ISSUE TITLE
Implement periodic automatic event exports

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#174]

**Comment by justpeanuts** [comment]
is this feature coming soon?
(it would be very useful feature indeed to sync personal calendars to personal devices without the need to sync using DecsyncCC (which has some bugs that make it stop working after some time for me), or, by setting up a caldav server (which is pretty daunting for newbies and also pretty-much overkill - to keep a server live and running all the time just to sync personal calendar) or, by using a third-party syncing (eg. google; the con being data privacy))

**Comment by tibbi** [comment]
not that soon, we will see

**Comment by dumblob** [comment]
IMHO periodic is not what users expect. I think that an automated export shall happen every single time anything changes in either of the calendars (be it due to recent sync or by the user) but not sooner than 2 seconds from the last **successful** backup (to avoid making 100 backups in one second e.g. due to running sync of many new calendars).

**Comment by justpeanuts** [comment]
OK.. Thank you for replying and for making these wonderfully simple apps!

30 Oct 2022, 21:00 by ***@***.***:

**Comment by tibbi** [comment]
not yet

**Comment by matusmlady** [comment]
> @tibbi Any update in this feature? Would cool to be able to have automatic backup every x hours like 6, 12, 24 setting etc and setting like keep last x backups 1, 2, 3, etc

Having a rooted phone I was able to set up automated backups using Neo Backup. I haven't tested recovering the data yet, but I assume it would work.
