### ISSUE TITLE
Create an option to customize notification behavior

### ISSUE THREAD

**Issue by Dilshan-H** [SimpleMobileTools/Simple-Calendar#1779]
First, thanks for maintaining these apps as FOSS. I love the whole Simple App series 🤩

**Identified Issue**

1. User creates a new event for a specific day and add reminders.
2. Simple Calendar shows notifications for the event.
3. As there are lots of notifications in notification panel user taps **Clear**.
4. Then there's a possibility that user forget about the event.

**What I suggest**

It would be great if there's an option to change event reminder notification behavior (when creating a new event) from standard notifications to persistent (sticky) notifications.

What I meant from that is adding a new action button named as **Done** in reminder notifications (aside with Snooze) for such events and set them as persistent notifications. So, when user taps **Clear** on notification panel the event reminder notification will not be removed.
Whenever user finishes the event, he/she can tap **Done** in notification and then it will be removed from the notification panel.

I'm not sure whether this might be possible or it will negatively affect battery usage. Just a suggestion 🤗

**Comment by tibbi** [comment]
thanks, but that is way too advanced for this app

**Comment by dumblob** [comment]
@Dilshan-H yes, one-off notifications have many different issues further amplified if there are multiple of them.

I can only recommend what BB10 Calendar did - see an older issue in this tracker: https://github.com/SimpleMobileTools/Simple-Calendar/issues/907

Also because such requests are getting rejected by upstream, we are considering forking Simple Calendar where such PRs could potentially be accepted - see https://github.com/SimpleMobileTools/Simple-Calendar/issues/1771#issuecomment-1176585779 and feel free to express your opinion. Thanks!
