### ISSUE TITLE
Add date and time option inside custom reminder

### ISSUE THREAD

**Issue by Pranab009** [SimpleMobileTools/Simple-Calendar#1806]
Add date and time option inside custom reminder.
This is too complicated to calculate.

![Screenshot_20220812-214818](https://user-images.githubusercontent.com/65340361/184410668-71647032-69a1-4e12-a2e5-9f3c36956ba8.png)

![Screenshot_20220812-214715_1](https://user-images.githubusercontent.com/65340361/184410660-fc0885e5-3434-411f-aaa8-b31ecf1f3c88.png)

![Screenshot_20220812-214750_1](https://user-images.githubusercontent.com/65340361/184410666-f05233b5-ea41-4ebf-94be-5b27c629e760.png)

**Comment by tibbi** [comment]
that is an edge case, you dont really set reminder to trigger 1 day and 7 minutes or so before the event often...

**Comment by Pranab009** [comment]
But if custom available then make it proper.
Custom means set everythings.
I have a event 10.08.22  10.00pm ok
If set set it as 1 day before then it remind me at

**Comment by tibbi** [comment]
so pick 26 hours, it is not a big deal.

**Comment by dumblob** [comment]
@Pranab009 what you are suggesting is what BB10 Calendar did.

Though because such requests are getting rejected by upstream, we are considering forking Simple Calendar where such PRs could potentially be accepted - see https://github.com/SimpleMobileTools/Simple-Calendar/issues/1771#issuecomment-1176585779 and feel free to express your opinion. Thanks!
