### ISSUE TITLE
Description of the event is missing with import

### ISSUE THREAD

**Issue by Tridy** [SimpleMobileTools/Simple-Calendar#1872]
Hi.

I am not sure if this is just me, but when I get an invite sent to me, such as an ics file, the event is imported, but the **Description** that includes a link to a Teams meeting is not imported, which becomes really annoying since I need to edit and copy it manually after the import.

Google calendar seems to do it properly, but Simple ignores the DESCRIPTION part of ics. A screenshot of the Simple vs Google calendar importing the same event and Simple showing Description missing:

<img src="https://i.postimg.cc/V6SwHnNG/calendars.png" height="350"/>

here is the content of the ICS file that I am trying to import:

https://pastebin.com/Kb6v6VvM

**Comment by Chris-GW** [comment]
The problem seems to be in line 24, as it contains the description with language parameter:
L. 24: `DESCRIPTION;LANGUAGE=en-US:New Year greetings [...]`

The current IcsImporter searches the beginning of the line for `"DESCRIPTION:"` and thus cannot recognise a `"DESCRIPTION;LANGUAGE=en-US:"`:
```kotlin
// IcsImporter at line 108:
if(line.startsWith("DESCRIPTION:") && !isNotificationDescription) {
    // set event description value
}
```


This seems to be a general problem with the current handling of .ics files. According to iCalendar (RFC 5545) no or more param are allowed in the contentline after the name of the property:
`contentline = name *(";" param ) ":" value CRLF`

**Comment by Sekhmet0208** [comment]
Hello could i work on this issue ? it would be my first issue, it's for a university project and i would solve it with @beastboym

**Comment by tibbi** [comment]
ye
