### ISSUE TITLE
Question: events updating automatically

### ISSUE THREAD

**Issue by Ypot** [SimpleMobileTools/Simple-Calendar#2042]
I would like to import my org-agenda events into Simple calendar.

But it would be important to be done automatically. For example, simple calendar updating the events some times a day with the new ics file.

Is it possible?

Note: I am not using Google calendar, and I don't want to use it

**Comment by tibbi** [comment]
since Simple Calendar is offline, it cannot take care of syncing the data between the device and the cloud directly. It needs a so called "sync adapter" for taking care of that syncing. For syncing via Google it is enough to have Google Calendar installed, it will take care of exchanging data between your device and the cloud. So if you have Google Calendar enabled on your device, you can try enabling "CalDAV sync" in the app settings, to see if some calendars show up. If the syncing is set up properly, you should see the same events in your device and on https://calendar.google.com/calendar/r . If you don't want to use Google, you can set up "DAVx5" app as the sync adapter too.

**Comment by Ypot** [comment]
Thanks. I would use synching to import the ICS file, no need of cloud.

Is that file what I was asking if could be automatically imported into Simple Calendar.
