### ISSUE TITLE
Cannot reproduce build

### ISSUE THREAD

**Issue by user6529576559** [SimpleMobileTools/Simple-Calendar#209]
Since the app has access to network and also to storage and some other stuff therefore I wanted to recompile the code myself and make sure it does not do any stuff it should not.
I built the release APK but it was not the same what is downloadable from github.
And I don't just mean the signing of course.
The resources.arsc is very different. The released version is not just different compared to my build, but it is also smaller.
I also have these extra folders compared to what the released APK (2.6.1) has:
drawable-hdpi-v4
drawable-ldrtl-hdpi-v17
drawable-ldrtl-mdpi-v17
drawable-ldrtl-xxhdpi-v17
drawable-ldrtl-xxxhdpi-v17
drawable-mdpi-v4
drawable-xxhdpi-v4
drawable-xxxhdpi-v4

What concerns me more is the resources.arsc. Why is my build output different from the APK downloadable from github? Is the one on github is infected with something?

**Comment by tibbi** [comment]
Hey, the latest Github release was released 25 days ago, there were 117 commits since then. Ive rewritten a lot of things, mostly replaced Google Sync with a more general CalDAV sync. That also removed the internet permission and a couple other ones. The Github release is always built from the sources you see at the code, theres nothing shady going on in the background. Im not sure about how are those resource files generated, or why they differ, btw "rtl" means right-to-left. Im going on vacation now, then Ill publish a new version on both playstore, github, f-droid.

**Comment by tibbi** [comment]
the build is already on f-droid, you can try comparing them.
