### ISSUE TITLE
Events covering 2+ pages of weekly view only displayed on first page

### ISSUE THREAD

**Issue by TheCrazyMaffin** [SimpleMobileTools/Simple-Calendar#2135]
**Steps to reproduce**

1. Disable "Show events spanning across midnight at the top bar"
2. Switch to weekly view (e.g. viewing 7 days per page)
3. Create an event which is expected to display on two pages of the weekly view.

**Expected behaviour:** Event displays on all pages of the weekly view.

**Actual behaviour:** Event will be displayed on the first page of the weekly view where the start-date of the event is located, the second page will not show the event at all.

Screenshots showing this behaviour: [https://imgur.com/a/2DxW52I](https://imgur.com/a/2DxW52I)

Version 6.22.0 Pro, Android 13

**Comment by WessellUrdata** [comment]
I found a possible culprit to this issue:

https://github.com/SimpleMobileTools/Simple-Calendar/blob/dce40291ca9210bd4d463659c1be7781435d26c4/app/src/main/kotlin/com/simplemobiletools/calendar/pro/fragments/WeekFragment.kt#L541-L645

Using the sample event you made, which spans from Sept 6 to Sept 13, since the app draws event rectangles for every page and that page only, it's going to fail the check at Line 553 as `dayColumns` hold that page's dates. 

When you get to the week 36 page (Sept 4 to Sept 10), the app only checks and draws what should be that page (from Sept 6 to 10) and nothing beyond that.

When you get to the week 37 page (Sept 11 to Sept 17), `currentDayCode` (which is initialized to be Sept 6 for that page's check) is checked against `dayColumns` (which holds Sept 11 to Sept 17), the check will therefore fail, and the rectangles not drawn.

---

my brain hurts trying to wrestle with Kotlin, someone please take this over
