### ISSUE TITLE
Importing ics events does not include all events

### ISSUE THREAD

**Issue by kscz** [SimpleMobileTools/Simple-Calendar#233]
I attempted to export all the events in my calendar, and almost none of the birthdays appear when I import the ICS into another phone!

I included "past events" when exporting and still had the issue.

**Comment by tibbi** [comment]
I assume you set them to repeatable yearly on same day, right? Can you check if they are included in the .ics file itself? It is a simple text file, you can open it with any text editor. Just search for the event title at a "SUMMARY" field

**Comment by kscz** [comment]
Yes, I see the events in the ICS file itself.  Correct, these are yearly events

**Comment by tibbi** [comment]
It always seems to work fine to me. Can you maybe find out what do the wrong birthdays have in common? Can you maybe send me the data of an event, which doesnt get imported properly? I mean the part between the corresponding BEGIN:VEVENT and END:VEVENT in the .ics file. Thanks

**Comment by linuxcaffe** [comment]
I've been using (and enjoying) simpletools and simplecalendar, and trying to figure out how to use them with taskwarrior (as in taskwarrior.org running on android via termux and twc2 (https://play.google.com/store/apps/details?id=com.taskwc2&hl=en) by using an export2ics script like https://github.com/linuxcaffe/tw-import-export-scripts/blob/master/tw-export-ical.py

Complicated? .. somewhat

Worth it? .. i think it would be, as I'd like to use tw to manage/ schedule more tasks/ events.

So how is this related to the O.P?
Because to make it possible and to take full advantage of the standard (https://en.wikipedia.org/wiki/ICalendar) it would be spectacular if Simple-Calendar could;

- on import, validate iCalendar format, and import all valid properties, even if Simple-Calendar doesn't (yet) use/ display them.

- on export, export all properties, even if Simple-Calendar doesn't use them.

That way, other applications could use/ modify different properties of the *.ics file (UID, VTODO, VJOURNAL ORGANIZER, etc.) and as long as Simple-Calendar didn't choke on import, and faithfully exported valid all .ics properties, it could work with all kinds of stuff!

$0.02 CDN, thanks :)

**Comment by tibbi** [comment]
Hey, I dont really want to handle properties Im not using for now. I just plan adding a Location field someday, not much is on the roadmap now.
