### ISSUE TITLE
Export does not follow iCalendar file format standard

### ISSUE THREAD

**Issue by dragonmaus** [SimpleMobileTools/Simple-Calendar#256]
The .ics files created by the export function are not valid iCalendar format files, as specified in [RFC 5545](https://tools.ietf.org/html/rfc5545).
This causes issues with other tools that read and write .ics files.

For example, they do not contain the "PRODID" or "VERSION" fields.

**Comment by tibbi** [comment]
I have added some PRODID and VERSION fields. Let me know if theres more issues, I dont feel like reading the whole specification :)

**Comment by Narrat** [comment]
Kinda stumpled upon this.
If I check a file with exported entries via the iCalendar validator (https://icalendar.org/validator.html) I get the following result (123 entries with 342 errors):
```
Lines not delimited by CRLF sequence (Reference: RFC 5545 3.1. Content Lines) (obviously only one occurence)
Missing DTSTAMP property (Reference: RFC 5545 3.6.1. Event Component)
Missing DESCRIPTION property in VALARM (Reference: RFC 5545 3.6.6. Alarm Component)
```
Just noticed this after I tried to import the exported .ics file into another calendar and the import failed completly. (No I don't want to get rid of this excellent app :D Just venturing into the topic of syncing, DAV and such)
Kinda seems like nitpicking from the spec looking at the `CRLF` vs `LF` topic.
Regarding `DESCRIPTION` the spec want it to be available, if the action is `DISPLAY`. So in those cases there should be an empty one written to the file? (And am I a bad user because I often don't set a description? :D)
But not sure about the `DTSTAMP` one. Is it about the timestamp when the `VEVENT` got created?
