### ISSUE TITLE
Do not percieve all numbers as phone numbers

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#382]

**Comment by SylvainGirod** [comment]
Hi, I could not reproduce the bug.
Could you, please, provide more details, like the number which gave you the error ?

**Comment by tibbi** [comment]
Im not sure, a user reported it. Just try adding numbers in a different format in the description, maybe start them with a Plus or zero

**Comment by SylvainGirod** [comment]
I couldn't reproduce the problem.
Did the user have a samsung phone ? Looks like some of their ROM's API are kinda weird, including one which is used by Android to match the phone numbers.

I tried to find a good fix to this, but it seems that in order to fix this bug, the method would be to recode a worldwide phone number parser...

Looks big for a "bug" which is very hard to find.

**Comment by tibbi** [comment]
I dont know, thats how programming works. Some problems appear only on some devices.

**Comment by tibbi** [comment]
was probably a samsung specific issue
