### ISSUE TITLE
Add an option to set the refresh interval for CalDAV

### ISSUE THREAD

**Issue by ettom** [SimpleMobileTools/Simple-Calendar#573]
It seems to be a bit slow now, I mostly manually refresh the calendars. Manually syncing from DAVdroid doesnt seem to refresh Simple-Calendar.

**Comment by tibbi** [comment]
it is 4 hours, or at opening the app. But the app really has to start after leaving it with the back button or swiping away, not just be resumed after leaving with the home button.

**Comment by dkaparis** [comment]
So if I understand correctly, the calendar should update after 4 hours. This doesn't work for me however - I just reproduced the problem where I add an event in Nextcloud and it doesn't show up in the app even after more than 4 hours.

This is a major drawback for me as I need to remember to restart my app (or refresh CalDAV calendars manually) every time I add or modify an event externally, if I want to rely on notifications on phone.

I think the ability/option to synchronize in background would be very useful.

**Comment by michaelof** [comment]
@dkaparis: There seems to be something special on your side, additionally.

I can 100% reproducible confirm:
- All calendar entries which I've made outside SimpleCalendar, directly in my Nextcloud, on another device, or in stock calendar app, will find their way into SimpleKalendar on their own. Maybe, as I have a device with just 1GB RAM, because I'm ususally wipe out apps from list of porn apps after usage, restarting them always, when needed again.
- I can also confirm, that a manual DAVdroid sync 100% reproducible adds missing Nextcloud calendar entries, at once.

One "speciality" found today, maybe related: I've created a new contact in SimpleContacts, with birthday defined, has been today :) To be stored in my Nextcloud. As DAVdroid's sync options are always <desired frequency> plus "immediately for local changes", my contact was at once in my Nextcloud. Visible very soon, not checked how long, stock calendar app showed new birthday entry. Whyever, SimpleCalendar does NOT show the birthday if the SimpleContacts' added new cardDAV/Nextcloud contact. BUT: A "refresh calDAV calendars" inside SimpleCalendar triggered a manual Nextcloud refresh an fetched the missing birthday.

**Comment by michaelof** [comment]
Un-be-liev-ab-le: my anysoft keyboard auto-substituted "open apps" with "porn apps" in my post above, no idea how this could happen, as it seems to be not reproductibke, strange..... :-S
Good luck I'm always reading again my posts.

**Comment by dkaparis** [comment]
Backing out of the app or wiping it from recent apps list and then opening it again will synchronize events (probably what you are observing).

The problem is e.g. when you leave the app with the home button and leave it in the background - in this case, according to what @tibbi wrote, it should synchronize itself within 4 hours, but that doesn't happen for me.

**Comment by michaelof** [comment]
As im not patient enough to wait 4 hours now, I'll try to check this night, how it works on my device. Will open SimpleCalendar and let it open during night, and add a Nextcloud cal entry on another device. Let's see :)

**Comment by spocko** [comment]
I concur with this feature request. If it is implemented, I suggest that a value of zero should disable scheduled refresh. Refresh can still be performed when the app is first opened, or when the user selects the option to manually refresh.

**Comment by tibbi** [comment]
starting from 6.4.0 on Android 7+ there will be a background job listening for CalDAV related updates, so it should work a lot better.
