### ISSUE TITLE
couldn't sync 3d-party calendars without using google calendar

### ISSUE THREAD

**Issue by lvmm** [SimpleMobileTools/Simple-Calendar#634]
When I installed simple calendar on my new phone I could see my own calendar but not 3d-party (other) calendars I synced with my old phone even though 'settings-calDAV sync' was on and in 'settings-manage synced calendars' all these 3d-party calendars were visible, switched on and checked in 'filter events by type' too. Pressing 'refresh caldav calendars' didn't help. Only after I turned on syncing for each of the 3d-pary calendars in the google calendar and pressed 'refresh caldav calendars' again in the simple calendar my 3d-party calendars finally became visible again. In other words you cannot set up a 3d-party calendar in simple calendar alone but will need google calendar for that - not nice. 4.2.0, android 8.1.

**Comment by tibbi** [comment]
ye, that is currently the expected behaviour, described at the app FAQ too. You need a third party sync adapter for taking care of the synchronization between your device and the servers. It can be google calendar, but also davdroid, acaldav, or some other app. Since it requires internet and it isnt easy to implement at all, Simple Calendar will not be getting a sync adapter anytime soon.
