### ISSUE TITLE
Weekly View: Start day at / End day at

### ISSUE THREAD

**Issue by knut-hildebrandt** [SimpleMobileTools/Simple-Calendar#646]
I'm not sure if this behavior is intended but other calendar application handle it differently. If I set "Start day at" to value other than 0 and "End day at" to a value other than 24 only that portion of the day is  shown in Weekly View and I can't even scroll before or after the times set.

I would expect  that only the time span shown by default is that by these values, but that I can scroll back and forward anyway. As it is now, I have to choose 0 and 24 respectively to also access the occasional earlier or later events, what causes Weekly View always to start at midnight. This I consider a bit inconvenient.

**Comment by roynico** [comment]
I fully support this change request and the description made by @knut-hildebrandt: The available time span should always be from 00 to 24 (in order to access, rare but existing events happening at very unreasonable time!), and one should be able to set the time span that is displayed at once (without having to scroll)
