### ISSUE TITLE
Per ICSDroid synced iCal is shown doubled in pro version 6.0.0

### ISSUE THREAD

**Issue by ouzowtf** [SimpleMobileTools/Simple-Calendar#698]
The same calendar shows fine just once per event in 5.1.2

**Comment by tibbi** [comment]
I cannot reproduce it :/ Does it always happen? Even at some single one-time event that you never modified, just created?

**Comment by ouzowtf** [comment]
I unchecked the calendar at the "synchronized calendar" menu and checked it again.
Now it's shown only one time per event again.
Last time this behavior popped up after some time and not from the beginning, too.
But I'll close the issue till it happens again.
Thanks.

**Comment by tibbi** [comment]
alright, glad it works. Also update the app to 6.0.1 whenever it becomes available, some glitches have been fixed.

**Comment by michaelof** [comment]
@tibbi 
This issue is a 100% duplicate of my old (and recently closed by you) issue #510

**Comment by tibbi** [comment]
weird that I cannot reproduce it with nextcloud either. Does it happen to single-occurrence events that were just created, and never modified in any way too? Or it affects only some more advanced events, like repeating ones etc?

**Comment by michaelof** [comment]
yes, it's weird. And I have absolutely no idea why and when it happens. It starts after a while, and the amount of "duplicates" is chaging, my maximum was 4. "Duplicates" in quotes, they're no real duplicates, they're just shown more than once. 
And, not all events are "duplicated", only some of them. No rules recognizable, even if some events are getting duplicated once, the might be staying single next time. and others will duplicated.

To your question:
Happens with all sorts of events, repeatable, single occurrences. 
And it happens with all version of SimpleCalendar since v4.0.4, I followed every release.

As said in my issue #510 : Good luck there's a simple worlaround: Just disable calDAV sync for a moment, and re-enable it. SimpleCalendar nicely remembers the last to-be-synced calendars as selected before, so in fact the workauround will just need 2 clicks.

**Comment by michaelof** [comment]
As these events are events I (really) need, I didn't try to delete them. But can do next time when I'll see duplicated events. Will also try to export to .ics, never did.

What I meant is that updating one of them updates them all. Not sure if this is shown immediately in SimpleCalendar, or after the next server sync (DAVdroid).

**Comment by tibbi** [comment]
you can trigger manual updates either in davdroid, or in simple calendar too. Either via menu -> Refresh CalDAV calendars, or by pull-to-refresh from the top on some views. But if updating one updates all of them, I guess the same one will be with deleting. You can create some dummy events for testing. But make sure you use version 6.0.1 and have some backups, just in case.

**Comment by ouzowtf** [comment]
It didn't happen again for me since yesterday.
I knock on wood this is automagically fixed.

**Comment by ouzowtf** [comment]
Just opened Simple Calendar and saw the iCal events were shown five times per event.
But a few seconds later the view was cleared to only one time per event.
I checked ICSDroid and the last sync was a few seconds ago.
This can't be an accident, so I think the "CalDav sync" of Simple Calendar triggered ICSDroid to sync the iCal again.

**Comment by michaelof** [comment]
@ouzowtf: How many different calDAV calendar sources are you syncing? I've got the slight idea that the amount of duplicates might be related to the number of calendars, not sure:

I've nearly got the same than @ouzowtf yesterday. When creating another nextcloud calender, for testing with this bug, recheck for ex. calenders in DAVdroid, sync, set SimpleCalendar to use this new calendar, SimpleCalendar immediately starts to duplicate nearly all other events, in already existing calendars :-S 
This time up to 5 duplicates, one more than before, as above: Maybe related to the one more calendar?

NONE  of the test events in the new calendar got duplicated, weird...

Happens just one time, but this time just disabling calDAV sync didn't help, duplicates have been left over. Had to manually delete all app data for SimpleCalendar, and reconfigure again. No duplicates since then.

PLUS: I've tested with an existing duplicate, as @tibbi asked me:

- Changing one of n duplicates does NOT change anything in SimpleCalendar except the event changed, all other duplictes stay as they are.

BEGIN:VCALENDAR
PRODID:-//Simple Mobile Tools//NONSGML Event Calendar//EN
VERSION:2.0
BEGIN:VEVENT
SUMMARY:Summary
UID:Caldav-12-2342
CATEGORY_COLOR:-8853644
CATEGORIES:Familienkalender
LAST-MODIFIED:19700101T000000Z
LOCATION:MyLocation
DTSTART:20181114T113500Z
DTEND:20181114T120000Z
STATUS:CONFIRMED
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-P0DT3H0M0S
END:VALARM
END:VEVENT
BEGIN:VEVENT
SUMMARY:Summary X
UID:0
CATEGORY_COLOR:-8853644
CATEGORIES:Familienkalender
LAST-MODIFIED:20181119T153115Z
LOCATION:MyLocation
DTSTART:20181114T113500Z
DTEND:20181114T120000Z
STATUS:CONFIRMED
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-P0DT3H0M0S
END:VALARM
END:VEVENT
END:VCALENDAR

(Event with Summary = "Summary X" was the changed event, UID:0)

- Having set DAVdroid to sync each hour plus at once for local changes, the changed event very fast appears in nextcloud
- After the next manual calDAV sync, the duplicate disappeared in SimpleCalendar. ONLY for this event, all other unaffected duplicates stay as they are.

**Comment by ouzowtf** [comment]
At the moment I see the events five times.

I have three calendar sources:

1) five CalDAV calendars from mailbox.org, synchronized via DAVDroid

2) one Outlook calendar

3) one webcal/iCal calendar (from calovo.de), synchronized via ICSDroid, because DAVDroid does not support this

The described behavior happens ONLY for the third case!
Seeing the events five times at the moment is a coincidence in my view, because sometimes they're doubled, sometimes tripled and now five times.

I didn't change the number of calendars or calendar sources, except of temporary unchecking the CalDav sync trying to fix the issue.

**Comment by michaelof** [comment]
@tibbi Just started SimpleCalendar to change an event. And because my device has not that much  memory (1GB), it took a while to swap some apps and "activate" SimpleKalendar. Doing this, I could "live" watch the duplication: Starting in daily view, a single event suddenly get's duplicated, three occurrences this time.

Fascinating ... could it be related to power save mode, somehow?

**Comment by tibbi** [comment]
I dont see how could it be related, not sure. Im working on something else now, will get to the calendar soon. Then Ill read this all and try reproducing it somehow.

**Comment by tibbi** [comment]
retest with 6.1.0, I rewrote some caldav related things. Syncing might be slower now, but more reliable.

**Comment by ouzowtf** [comment]
Did not see any multiplied events since updating to 6.1.0 yesterday
