### ISSUE TITLE
Disable automatically birthdays/anniversaries insertion

### ISSUE THREAD

**Issue by schlagi123** [SimpleMobileTools/Simple-Calendar#710]
Hello, 

it were greate, if there are an option to disable the automatically insertion of birthdays/annicersaries. 
The situation: Somewhan I clicked on the menu point "add birthday of contacts" (Ger: "Geburtstage der Kontakte hinzufügen"). Now I do not want this anymore, because I have an extra app for birthdays so that I have deleted all the birthday and annicersarie dates from my calender. But everytime I change the data of a contact, birthdays and annicersaries will be added in my calender. I want to disable that. 

Morover ever change result in a new date for birthdays and annicersaries so that the birthdays/annicersaries are multiple times there.

Version: 6.0.1

**Comment by tibbi** [comment]
That menu item for adding birthdays is not automatic, maybe you enabled some CalDAV calendar that is doing it. Check the "Manage synced calendars" under CalDAV in the app settings for it. You can remove the old birthdays/anniversaries in settings -> manage event types.

**Comment by knut-hildebrandt** [comment]
@schlagi123 Have got the same problem. I use Birthday Adapter to integrate my contacts birthdays into simple calendar. And they keep multiplying. How did you delete the multiplying birthdays and the ones imported by "Import contact birthdays"? Unchecking "Geburts- und Jahrestage" - "Birthdays and Aneversaries" did not do the job.

BTW. both my contacts and the calender reside on a Nextcloud and are synchronized using DAVdroid.

**Comment by michaelof** [comment]
@knut-hildebrandt: Not sure why you use/need the additional Birthday Adapter.app, or the "insert contacts birhdays" function. You said you're using Nextcloud, synced with DAVdroid. Same than I do, so you also must see a "Contacts Birtgdays" calender automatically in DAVdroid. Just enable this in SimpleCalendars calDav settings, and you're done.

**Comment by schlagi123** [comment]
Google was the problem by me. After I change my calendar and contacts syncronisation to my own nextcloud, the problem was solved. I do not know the problem in detail.

**Comment by knut-hildebrandt** [comment]
@schlagi123: Thanks for the quick reply. Well, I had the problem with Nextcloud and only could get rid of all the leftovers by un- and reinstalling the app.

@michaelof: First of all I could not use birthday calendar from my Nextcloud due to this issue: https://help.nextcloud.com/t/how-can-i-create-the-birthdays-calendar-again/7020

After re-reading this thread today I re-enabled birthday calendar with the command line instructions given at it's end. This was not possible yet since I could not use ssh on my web space until recently.

But there is one problem still prevailing, I only can configure the reminders entry by entry, because there is no way to set them for all the calendar. Birthday Adapter solved this problem in an excellent way by offering presets for up to three reminders.

**Comment by schlagi123** [comment]
@knut-hildebrandt Yes you are right. Thats an issue by nextclout (https://github.com/nextcloud/server/issues/1505). And you cannot change this remainders in the calendar, because this is a read only calendar of the nextcloud.
