### ISSUE TITLE
Missing some german holidays

### ISSUE THREAD

**Issue by MyLogins** [SimpleMobileTools/Simple-Calendar#822]
Following german holidays missing afther import holidays:

- Internatinaler Frauentag
- Reformationstag
- Buß- und Bettag

**Comment by tibbi** [comment]
actually I added only holidays which mean free days. Not Womens day etc.

**Comment by MyLogins** [comment]
All three are official holidays, which are also free.

**Comment by tibbi** [comment]
Hm, you dont go to school/work on Womens' day?

**Comment by MyLogins** [comment]
Yes, in Berlin.

https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland#%C3%9Cbersicht_aller_gesetzlichen_Feiertage

**Comment by tibbi** [comment]
ok, Ill take a look at it. Thanks

**Comment by Anke** [comment]
Well... This is stressing the term "legal holidays" a bit, dom't you think? IMHO naming federal holidays is good enough, as you can add local holidays as you please. 

Otherwise a LOT of foot notes for state-specific holidays/exceptions would have to be included. 
Or either they'd have to offer different import holiday files for each state, as a Hesse or a Bavarian usually doesn't care if Women's day is a legal holiday in Berlin. Including all regional holidays would make the holiday calendar rather confusing.

**Comment by michaelof** [comment]
Aren't we reinventing the wheel here? Google/Android itself is aware of public holidays, shown to me as "Feiertage in Deutschland" Gmail kalendar. Which is the only Gmail kalendar I'm using :)
Also e.g. school holidays, could be downloaded and imported from http://schulferien.org

**Comment by MyLogins** [comment]
Only "Reformationstag" is important for me. The other two was only for the sake of completeness. It was never my intention to start a discussion about Women's day.

> IMHO naming federal holidays is good enough, as you can add local holidays as you please. 

However following local holidays are already included:

- Heilige Drei Könige
- Fronleichnam
- Friedensfest
- Maria Himmelfahrt
- Allerheiligen
- Volkstrauertag (no holiday but commemoration day)
- Totensonntag (also no holiday)

**Comment by Anke** [comment]
Oh, I see. You're right. That would be a little inconsistent. I was missing Ostersonntag and Pfingstsonntag e.g.

**Comment by hurzl** [comment]
Es können leider die Feiertage nicht nach den verschiedenen Bundesländern importiert werden, die unterscheiden sich nämlich

**Comment by tibbi** [comment]
seems like those holidays are quite messed up, different per land. Anyway I added those 3 top reported events, thats what this issue was about. Internatinaler Frauentag and Reformationstag are proper repeating events, Buß- und Bettag has been hardcoded till 2023 as it has quite a difficult repetition rule.
