### ISSUE TITLE
highish CPU usage

### ISSUE THREAD

**Issue by lvmm** [SimpleMobileTools/Simple-Calendar#861]
Recently I noticed that my battery lasts less than it used to be. I checked app usage and what do you know - Simple Calendar is the top battery user. It's not a complete disaster, but more than can be expected from a calendar app. Screenshots with and without system apps are below. Simple Calendar Pro 6.4.3 last updated on April 10, but it could've started earlier. CalDAV sync is on, android 8.1.

![Screenshot_20190416-141204](https://user-images.githubusercontent.com/11752339/56205358-3ab47300-6052-11e9-97bd-131086e42023.png)
![Screenshot_20190416-141210](https://user-images.githubusercontent.com/11752339/56205359-3b4d0980-6052-11e9-9927-df93451794e4.png)

**Comment by tibbi** [comment]
I dont think there is anything to do on our side, maybe something got stuck somewhere. CalDAV sync has been adjusted too since then already.

**Comment by Valentin-N** [comment]
I'm sad to see this report was so easily dismissed. I have been seeing this issue for a while now and I keep trying the app to see if anything has changed and then uninstalling it since it just murders my battery with only 2 calendars (Google and Exchange).

I gave it a try again today, roughly one year after I originally noticed the bad behavior, only to see nothing has changed.

Using a live process viewer (System Panel) I can see that both Calendar Storage and (Simple) Calendar both spiking to 5-10% CPU each about once every 5 seconds when WebDAV is enabled. Uninstalling (Simple) Calendar fixes this and Calendar Storage goes back to normal (i.e. no CPU usage).
