### ISSUE TITLE
Check toast about next reminder not being shown

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#882]

**Comment by rjain90** [comment]
Hey @tibbi Can you describe this?

**Comment by tibbi** [comment]
well everytime you create an event with some reminder set, the time remaining till the next reminder is shown. In some cases it might not work, not sure when.

**Comment by archibishop** [comment]
Hey @tibbi tried walking through the code. I assume the issue is the toast cannot be shown since the `EventActivity` is either finishing or has been destroyed. i was following the code with break points and the toast within in the if was not executed. However these lines are part of the `com.simplemobiletools:commons` library and its read-only. Hope this is helpful. Thanks.

##### Snippet from the `com.simplemobiletools:commons` library.
```
private fun doToast(context: Context, message: String, length: Int) {
    if (context is Activity) {
        if (!context.isFinishing && !context.isDestroyed) {
            Toast.makeText(context, message, length).show()
        }
    } else {
        Toast.makeText(context, message, length).show()
    }
}
```

**Comment by tibbi** [comment]
well it works just fine in the vast majority of cases, the activity should still be alive at that time

**Comment by archibishop** [comment]
The method `getEvents` creates another thread  since its making some queries to the db thus `finish()` is in the `EventActivity` is executed as this continues in the background. Thus causing the activity to be destroyed.
```
eventsHelper.getEvents(now, now + YEAR, event.id!!, false) {
        if (it.isNotEmpty()) {
            for (curEvent in it) {
                for (curReminder in reminderSeconds) {
                    if (curEvent.getEventStartTS() - curReminder > now) {
                        scheduleEventIn((curEvent.getEventStartTS() - curReminder) * 1000L, curEvent, showToasts)
                        return@getEvents
                    }
                }
            }
        }

        if (showToasts) {
            toast(R.string.saving)
        }
    }
```
