### ISSUE TITLE
Reminders of all-day events

### ISSUE THREAD

**Issue by smnthermes** [SimpleMobileTools/Simple-Calendar#953]
When the option "all-day" is turned on, the reminders are also set before the event. It would actually make more sense if the reminders were set in a determined time of the day.

**Comment by Spielmops** [comment]
One solution for this: custum time and the minus-sign before the numbers. The number-keyboard shows the sign, but I cannot insert it.
Spielmops

**Comment by t-m-w** [comment]
There is a small bug that would likely be solved by this feature request, but may not be deserving of its own issue (I'm not sure) — if you are using CalDAV calendars and you look at an event which already has reminders for *after* the event start (like an all-day event with a reminder at 10:00 and 19:00 that day), you will see those reminders as negative (-10 and -19), but the units will show as minutes rather than hours. Although they show as negative, it remains impossible to enter a negative value manually.
One reason users might want this is if they are migrating from Google Calendar, which seems to encourage same-day reminders for all-day events, and treats all-day events differently by giving them their own default reminder settings. On the other hand, other apps like the AOSP calendar or Etar do not allow setting these reminders either, but they show them in the correct units.

**Comment by tibbi** [comment]
during day reminders for all-day events will be added in 6.12.0
